name: ci

on:
  push:
  pull_request:
    types: [ opened, reopened ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 3m0s
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Test
        run: make test
